name: build-source

on:
  push:

jobs:

  source:
    runs-on: ubuntu-22.04
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: distrho/dpf-makefile-action@v1
        with:
          target: source

